---
title: 'Shrimp Scoping Key Statistics'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
require(stringr)
require(gsubfn)
require(dplyr)
require(readxl)
require(data.table)
require(libamtrack)
require(aws.s3)
require(knitr)

options(scipen=999999999)

setwd('C:/Users/laura.delduca/Desktop/code')

## not needed: current_folder <- '1009'
## not needed: script_folder <- 's3inventory/comtrade_checks'

source('R_aws.s3_credentials.R')
```

Countries requested so far are: Argentina, Colombia, Ecuador, Peru, Indonesia, India, Vietnam

## Production

Source: Jon's compilation of FISHSTATJ shrimp data (FAOSTAT)

```{r, include=FALSE}
## load FISHSTAT (FAO) data 
obj <- get_object(object = 'data/1-TRADE/STATISTICAL_DATA/GLOBAL/FAOSTAT/fishstatj_shrimp_global.csv', bucket = 'trase-storage')
fishstat <- read.csv(text = rawToChar(obj), quote = '', sep = ';')

## substitute 0 for '...' or '-', delete 'F'
fishstat$X2013 <- as.numeric(gsub("F", "", as.character(fishstat$X2013)))
fishstat$X2014 <- as.numeric(gsub("F", "", as.character(fishstat$X2014)))
fishstat$X2015 <- as.numeric(gsub("F", "", as.character(fishstat$X2015)))
fishstat$X2016 <- as.numeric(gsub("F", "", as.character(fishstat$X2016)))

## table with: year, total production volume, top ten producers with volume and percentage
## only countries and year column
fishstat_2013 <- data.frame(fishstat$'Country..Country.', fishstat$X2013)[order(-fishstat$X2013),] 
names(fishstat_2013) <- c('Country', 'Volume (tonnes)')
fishstat_2014 <- data.frame(fishstat$'Country..Country.', fishstat$X2014)[order(-fishstat$X2014),] 
names(fishstat_2014) <- c('Country', 'Volume (tonnes)')
fishstat_2015 <- data.frame(fishstat$'Country..Country.', fishstat$X2015)[order(-fishstat$X2015),] 
names(fishstat_2015) <- c('Country', 'Volume (tonnes)')
fishstat_2016 <- data.frame(fishstat$'Country..Country.', fishstat$X2016)[order(-fishstat$X2016),] 
names(fishstat_2016) <- c('Country', 'Volume (tonnes)')
total_2013 <- fishstat_2013$'Volume (tonnes)'[1]
total_2014 <- fishstat_2014$'Volume (tonnes)'[1]
total_2015 <- fishstat_2015$'Volume (tonnes)'[1]
total_2016 <- fishstat_2016$'Volume (tonnes)'[1]

fishstat_2013 <- fishstat_2013[-1,]
rownames(fishstat_2013) <- c()
fishstat_2014 <- fishstat_2014[-1,]
rownames(fishstat_2014) <- c()
fishstat_2015 <- fishstat_2015[-1,]
rownames(fishstat_2015) <- c()
fishstat_2016 <- fishstat_2016[-1,]
rownames(fishstat_2016) <- c()

fishstat_2013$'Percent of total' <- round( fishstat_2013$`Volume (tonnes)`/total_2013 , digits = 3)
fishstat_2014$'Percent of total' <- round( fishstat_2014$`Volume (tonnes)`/total_2014 , digits = 3)
fishstat_2015$'Percent of total' <- round( fishstat_2015$`Volume (tonnes)`/total_2015 , digits = 3)
fishstat_2016$'Percent of total' <- round( fishstat_2016$`Volume (tonnes)`/total_2016 , digits = 3)
```

```{r, echo = FALSE, results = 'asis'}

# Requested countries
countries <- c('Argentina', 'Colombia', 'Ecuador', 'Peru', 'Indonesia', 'India', 'Viet Nam')

kable(fishstat_2013[1:10,], caption = 'Production top ten countries 2013')
fishstat_2013_countries <- fishstat_2013[fishstat_2013$Country %in% countries,]
rownames(fishstat_2013_countries) <- c()
kable(fishstat_2013_countries, caption = 'Production of requested countries 2013')

kable(fishstat_2014[1:10,], caption = 'Production top ten countries 2014')
fishstat_2014_countries <- fishstat_2014[fishstat_2014$Country %in% countries,]
rownames(fishstat_2014_countries) <- c()
kable(fishstat_2014_countries, caption = 'Production of requested countries 2014')

kable(fishstat_2015[1:10,], caption = 'Production top ten countries 2015')
fishstat_2015_countries <- fishstat_2015[fishstat_2015$Country %in% countries,]
rownames(fishstat_2015_countries) <- c()
kable(fishstat_2015_countries, caption = 'Production of requested countries 2015')

kable(fishstat_2016[1:10,], caption = 'Production top ten countries 2016')
fishstat_2016_countries <- fishstat_2016[fishstat_2016$Country %in% countries,]
rownames(fishstat_2016_countries) <- c()
kable(fishstat_2016_countries, caption = 'Production of requested countries 2016')

```


## Exports

Relative importance of exports for a country is included as percentage of GDP.

Source: COMTRADE (trade data), OECD (GDP)

```{r, include=FALSE}
## COMTRADE

## Need to preprocess COMTRADE and filter for shrimp codes
obj <- get_object(object = 'data/1-TRADE/STATISTICAL_DATA/GLOBAL/COMTRADE/COMTRADE_SHRIMP/COMTRADE_2013_shrimp.csv', bucket = 'trase-storage')
comtrade13 <- read.csv(text = rawToChar(obj), quote = '', sep = ';')
obj <- get_object(object = 'data/1-TRADE/STATISTICAL_DATA/GLOBAL/COMTRADE/COMTRADE_SHRIMP/COMTRADE_2014_shrimp.csv', bucket = 'trase-storage')
comtrade14 <- read.csv(text = rawToChar(obj), quote = '', sep = ';')
obj <- get_object(object = 'data/1-TRADE/STATISTICAL_DATA/GLOBAL/COMTRADE/COMTRADE_SHRIMP/COMTRADE_2015_shrimp.csv', bucket = 'trase-storage')
comtrade15 <- read.csv(text = rawToChar(obj), quote = '', sep = ';')
obj <- get_object(object = 'data/1-TRADE/STATISTICAL_DATA/GLOBAL/COMTRADE/COMTRADE_SHRIMP/COMTRADE_2016_shrimp.csv', bucket = 'trase-storage')
comtrade16 <- read.csv(text = rawToChar(obj), quote = '', sep = ';')

## _________
## 2013

comtrade_export <- comtrade13[(comtrade13$flow == 'Export') & (comtrade13$partner == 'World'),]

total_export <- data.frame('country' = comtrade_export$country,
				'netweight_kg' = comtrade_export$netweight_kg, 
				'value_USD' = comtrade_export$value_USD)

# sum by country
total_export <- aggregate(cbind('netweight_kg' = total_export$netweight_kg, 
                                   'value_USD' = total_export$value_USD),
                             by=list(country=total_export$country),
                             FUN=sum, 
                             na.rm=TRUE)
total_export <- total_export[order(-total_export$netweight_kg),] 

# add gdp and %
iso <- fread('C:/Users/laura.delduca/Desktop/isocodes.csv')
total_export$iso <- iso$ISO3[match(toupper(as.character(total_export$country)), as.character(iso$COUNTRY))]
total_export$iso[total_export$country == 'Viet Nam'] <- 'VNM'

# load OECD GDP data
obj <- get_object(object = 'data/1-TRADE/STATISTICAL_DATA/GLOBAL/OECD/OECD_GDP_YEARLY.csv', bucket = 'trase-storage')
gdp <- read.csv(text = rawToChar(obj), quote = '', sep = ';')
gdp <- gdp[gdp$MEASURE == 'MLN_USD',]
gdp_year <- gdp[gdp$TIME == 2013,]

# add GDP and percentage
total_export$gdp_MLN_USD <- as.numeric(gdp_year$Value[match(total_export$iso, gdp_year$LOCATION)])
total_export$value_per_gdp <- round( total_export$value_USD / total_export$gdp_MLN_USD , digits = 2)

# drop iso column
total_export <- select(total_export, -iso)
```

```{r, echo = FALSE, results = 'asis'}

rownames(total_export) <- c()
kable(total_export[1:10,], caption = 'Top ten exporting countries 2013')
total_export_countries <- total_export[total_export$country %in% countries,]
rownames(total_export_countries) <- c()
kable(total_export_countries, caption = 'Export of requested countries 2013')
```


```{r, include=FALSE}
## _________
## 2014

comtrade_export <- comtrade14[(comtrade14$flow == 'Export') & (comtrade14$partner == 'World'),]

total_export <- data.frame('country' = comtrade_export$country,
				'netweight_kg' = comtrade_export$netweight_kg, 
				'value_USD' = comtrade_export$value_USD)

# sum by country
total_export <- aggregate(cbind('netweight_kg' = total_export$netweight_kg, 
                                   'value_USD' = total_export$value_USD),
                             by=list(country=total_export$country),
                             FUN=sum, 
                             na.rm=TRUE)
total_export <- total_export[order(-total_export$netweight_kg),] 

# add gdp and %
total_export$iso <- iso$ISO3[match(toupper(as.character(total_export$country)), as.character(iso$COUNTRY))]
total_export$iso[total_export$country == 'Viet Nam'] <- 'VNM'

# load OECD GDP data
gdp_year <- gdp[gdp$TIME == 2014,]

# add GDP and percentage
total_export$gdp_MLN_USD <- as.numeric(gdp_year$Value[match(total_export$iso, gdp_year$LOCATION)])
total_export$value_per_gdp <- round( total_export$value_USD / total_export$gdp_MLN_USD , digits = 2)

# drop iso column
total_export <- select(total_export, -iso)
```

```{r, echo = FALSE, results = 'asis'}

rownames(total_export) <- c()
kable(total_export[1:10,], caption = 'Top ten exporting countries 2014')
total_export_countries <- total_export[total_export$country %in% countries,]
rownames(total_export_countries) <- c()
kable(total_export_countries, caption = 'Export of requested countries 2014')
```



```{r, include=FALSE}
## _________
## 2015

comtrade_export <- comtrade15[(comtrade15$flow == 'Export') & (comtrade15$partner == 'World'),]

total_export <- data.frame('country' = comtrade_export$country,
				'netweight_kg' = comtrade_export$netweight_kg, 
				'value_USD' = comtrade_export$value_USD)

# sum by country
total_export <- aggregate(cbind('netweight_kg' = total_export$netweight_kg, 
                                   'value_USD' = total_export$value_USD),
                             by=list(country=total_export$country),
                             FUN=sum, 
                             na.rm=TRUE)
total_export <- total_export[order(-total_export$netweight_kg),] 

# add gdp and %
total_export$iso <- iso$ISO3[match(toupper(as.character(total_export$country)), as.character(iso$COUNTRY))]
total_export$iso[total_export$country == 'Viet Nam'] <- 'VNM'

# load OECD GDP data
gdp_year <- gdp[gdp$TIME == 2015,]

# add GDP and percentage
total_export$gdp_MLN_USD <- as.numeric(gdp_year$Value[match(total_export$iso, gdp_year$LOCATION)])
total_export$value_per_gdp <- round( total_export$value_USD / total_export$gdp_MLN_USD , digits = 2)

# drop iso column
total_export <- select(total_export, -iso)
```

```{r, echo = FALSE, results = 'asis'}

rownames(total_export) <- c()
kable(total_export[1:10,], caption = 'Top ten exporting countries 2015')
total_export_countries <- total_export[total_export$country %in% countries,]
rownames(total_export_countries) <- c()
kable(total_export_countries, caption = 'Export of requested countries 2015')
```


```{r, include=FALSE}
## _________
## 2016

comtrade_export <- comtrade16[(comtrade16$flow == 'Export') & (comtrade16$partner == 'World'),]

total_export <- data.frame('country' = comtrade_export$country,
				'netweight_kg' = comtrade_export$netweight_kg, 
				'value_USD' = comtrade_export$value_USD)

# sum by country
total_export <- aggregate(cbind('netweight_kg' = total_export$netweight_kg, 
                                   'value_USD' = total_export$value_USD),
                             by=list(country=total_export$country),
                             FUN=sum, 
                             na.rm=TRUE)
total_export <- total_export[order(-total_export$netweight_kg),] 

# add gdp and %
total_export$iso <- iso$ISO3[match(toupper(as.character(total_export$country)), as.character(iso$COUNTRY))]
total_export$iso[total_export$country == 'Viet Nam'] <- 'VNM'

# load OECD GDP data
gdp_year <- gdp[gdp$TIME == 2016,]

# add GDP and percentage
total_export$gdp_MLN_USD <- as.numeric(gdp_year$Value[match(total_export$iso, gdp_year$LOCATION)])
total_export$value_per_gdp <- round( total_export$value_USD / total_export$gdp_MLN_USD , digits = 2)

# drop iso column
total_export <- select(total_export, -iso)
```

```{r, echo = FALSE, results = 'asis'}

rownames(total_export) <- c()
kable(total_export[1:10,], caption = 'Top ten exporting countries 2016')
total_export_countries <- total_export[total_export$country %in% countries,]
rownames(total_export_countries) <- c()
kable(total_export_countries, caption = 'Export of requested countries 2016')
```




## Imports

```{r, include=FALSE}

## _________
## 2013

comtrade_import <- comtrade13[(comtrade13$flow == 'Import') & (comtrade13$partner == 'World'),]

total_import <- data.frame('country' = comtrade_import$country,
				'netweight_kg' = comtrade_import$netweight_kg, 
				'value_USD' = comtrade_import$value_USD)

# sum by country
total_import <- aggregate(cbind('netweight_kg' = total_import$netweight_kg, 
                                   'value_USD' = total_import$value_USD),
                             by=list(country=total_import$country),
                             FUN=sum, 
                             na.rm=TRUE)
total_import <- total_import[order(-total_import$netweight_kg),] 

# add gdp and %
total_import$iso <- iso$ISO3[match(toupper(as.character(total_import$country)), as.character(iso$COUNTRY))]
total_import$iso[total_import$country == 'Viet Nam'] <- 'VNM'

# load OECD GDP data
gdp_year <- gdp[gdp$TIME == 2013,]

# add GDP and percentage
total_import$gdp_MLN_USD <- as.numeric(gdp_year$Value[match(total_import$iso, gdp_year$LOCATION)])
total_import$value_per_gdp <- round( total_import$value_USD / total_import$gdp_MLN_USD , digits = 2)

# drop iso column
total_import <- select(total_import, -iso)

```

```{r, echo = FALSE, results = 'asis'}
rownames(total_import) <- c()
kable(total_import[1:10,], caption = 'Top ten importing countries 2013')
total_import_countries <- total_import[total_import$country %in% countries,]
rownames(total_import_countries) <- c()
kable(total_import_countries, caption = 'Import of requested countries 2013')
```

```{r, include=FALSE}

## _________
## 2014

comtrade_import <- comtrade14[(comtrade14$flow == 'Import') & (comtrade14$partner == 'World'),]

total_import <- data.frame('country' = comtrade_import$country,
				'netweight_kg' = comtrade_import$netweight_kg, 
				'value_USD' = comtrade_import$value_USD)

# sum by country
total_import <- aggregate(cbind('netweight_kg' = total_import$netweight_kg, 
                                   'value_USD' = total_import$value_USD),
                             by=list(country=total_import$country),
                             FUN=sum, 
                             na.rm=TRUE)
total_import <- total_import[order(-total_import$netweight_kg),] 

# add gdp and %
total_import$iso <- iso$ISO3[match(toupper(as.character(total_import$country)), as.character(iso$COUNTRY))]
total_import$iso[total_import$country == 'Viet Nam'] <- 'VNM'

# load OECD GDP data
gdp_year <- gdp[gdp$TIME == 2014,]

# add GDP and percentage
total_import$gdp_MLN_USD <- as.numeric(gdp_year$Value[match(total_import$iso, gdp_year$LOCATION)])
total_import$value_per_gdp <- round( total_import$value_USD / total_import$gdp_MLN_USD , digits = 2)

# drop iso column
total_import <- select(total_import, -iso)

```

```{r, echo = FALSE, results = 'asis'}
rownames(total_import) <- c()
kable(total_import[1:10,], caption = 'Top ten importing countries 2014')
total_import_countries <- total_import[total_import$country %in% countries,]
rownames(total_import_countries) <- c()
kable(total_import_countries, caption = 'Import of requested countries 2014')
```


```{r, include=FALSE}

## _________
## 2015

comtrade_import <- comtrade15[(comtrade15$flow == 'Import') & (comtrade15$partner == 'World'),]

total_import <- data.frame('country' = comtrade_import$country,
				'netweight_kg' = comtrade_import$netweight_kg, 
				'value_USD' = comtrade_import$value_USD)

# sum by country
total_import <- aggregate(cbind('netweight_kg' = total_import$netweight_kg, 
                                   'value_USD' = total_import$value_USD),
                             by=list(country=total_import$country),
                             FUN=sum, 
                             na.rm=TRUE)
total_import <- total_import[order(-total_import$netweight_kg),] 

# add gdp and %
total_import$iso <- iso$ISO3[match(toupper(as.character(total_import$country)), as.character(iso$COUNTRY))]
total_import$iso[total_import$country == 'Viet Nam'] <- 'VNM'

# load OECD GDP data
gdp_year <- gdp[gdp$TIME == 2015,]

# add GDP and percentage
total_import$gdp_MLN_USD <- as.numeric(gdp_year$Value[match(total_import$iso, gdp_year$LOCATION)])
total_import$value_per_gdp <- round( total_import$value_USD / total_import$gdp_MLN_USD , digits = 2)

# drop iso column
total_import <- select(total_import, -iso)

```

```{r, echo = FALSE, results = 'asis'}
rownames(total_import) <- c()
kable(total_import[1:10,], caption = 'Top ten importing countries 2015')
total_import_countries <- total_import[total_import$country %in% countries,]
rownames(total_import_countries) <- c()
kable(total_import_countries, caption = 'Import of requested countries 2015')
```


```{r, include=FALSE}

## _________
## 2016

comtrade_import <- comtrade16[(comtrade16$flow == 'Import') & (comtrade16$partner == 'World'),]

total_import <- data.frame('country' = comtrade_import$country,
				'netweight_kg' = comtrade_import$netweight_kg, 
				'value_USD' = comtrade_import$value_USD)

# sum by country
total_import <- aggregate(cbind('netweight_kg' = total_import$netweight_kg, 
                                   'value_USD' = total_import$value_USD),
                             by=list(country=total_import$country),
                             FUN=sum, 
                             na.rm=TRUE)
total_import <- total_import[order(-total_import$netweight_kg),] 

# add gdp and %
total_import$iso <- iso$ISO3[match(toupper(as.character(total_import$country)), as.character(iso$COUNTRY))]
total_import$iso[total_import$country == 'Viet Nam'] <- 'VNM'

# load OECD GDP data
gdp_year <- gdp[gdp$TIME == 2016,]

# add GDP and percentage
total_import$gdp_MLN_USD <- as.numeric(gdp_year$Value[match(total_import$iso, gdp_year$LOCATION)])
total_import$value_per_gdp <- round( total_import$value_USD / total_import$gdp_MLN_USD , digits = 2)

# drop iso column
total_import <- select(total_import, -iso)

```

```{r, echo = FALSE, results = 'asis'}
rownames(total_import) <- c()
kable(total_import[1:10,], caption = 'Top ten importing countries 2016')
total_import_countries <- total_import[total_import$country %in% countries,]
rownames(total_import_countries) <- c()
kable(total_import_countries, caption = 'Import of requested countries 2016')
```


## Which CD export data HS codes should we buy?


```{r, include=FALSE}
comtrade_export <- comtrade16[(comtrade16$flow == 'Export') & (comtrade16$partner == 'World'),]

total_export <- data.frame('country' = comtrade_export$country,
                           'commodity' = comtrade_export$commodity,
                           'netweight_kg' = comtrade_export$netweight_kg)

codes <- data.frame(matrix(ncol = 7, nrow = 7))
colnames(codes) <- c('country', 'total_netweight_kg', '030616', '030617', '030635', '030636', '030695')
codes$country <- countries
codes$'030635' <- codes$'030636' <- codes$'030695' <- 0

total_country <- aggregate( x = total_export$netweight_kg,
                             by=list(country=total_export$country),
                             FUN=sum, 
                             na.rm=TRUE)

codes$total_netweight_kg[codes$country == 'Argentina'] <- total_country$x[total_country$country == 'Argentina']
codes$total_netweight_kg[codes$country == 'Colombia'] <- total_country$x[total_country$country == 'Colombia']
codes$total_netweight_kg[codes$country == 'Ecuador'] <- total_country$x[total_country$country == 'Ecuador']
codes$total_netweight_kg[codes$country == 'Peru'] <- total_country$x[total_country$country == 'Peru']
codes$total_netweight_kg[codes$country == 'Indonesia'] <- total_country$x[total_country$country == 'Indonesia']
codes$total_netweight_kg[codes$country == 'India'] <- total_country$x[total_country$country == 'India']
codes$total_netweight_kg[codes$country == 'Viet Nam'] <- NA

codes$`030616`[codes$country == 'Argentina'] <- 0
codes$`030616`[codes$country == 'Colombia'] <- round( total_export$netweight_kg[(total_export$country == 'Colombia') & (total_export$commodity == 30616)] / codes$total_netweight_kg[codes$country == 'Colombia'], digits = 3 )
codes$`030616`[codes$country == 'Ecuador'] <- round( total_export$netweight_kg[(total_export$country == 'Ecuador') & (total_export$commodity == 30616)] / codes$total_netweight_kg[codes$country == 'Ecuador'], digits = 3 )
codes$`030616`[codes$country == 'Peru'] <- round( total_export$netweight_kg[(total_export$country == 'Peru') & (total_export$commodity == 30616)] / codes$total_netweight_kg[codes$country == 'Peru'], digits = 3 )
codes$`030616`[codes$country == 'Indonesia'] <-round( total_export$netweight_kg[(total_export$country == 'Indonesia') & (total_export$commodity == 30616)] / codes$total_netweight_kg[codes$country == 'Indonesia'], digits = 3 )
codes$`030616`[codes$country == 'India'] <- round( total_export$netweight_kg[(total_export$country == 'India') & (total_export$commodity == 30616)] / codes$total_netweight_kg[codes$country == 'India'], digits = 3 )
codes$`030616`[codes$country == 'Viet Nam'] <- 0


codes$`030617`[codes$country == 'Argentina'] <- round( total_export$netweight_kg[(total_export$country == 'Argentina') & (total_export$commodity == 30617)] / codes$total_netweight_kg[codes$country == 'Argentina'], digits = 3 )
codes$`030617`[codes$country == 'Colombia'] <- round( total_export$netweight_kg[(total_export$country == 'Colombia') & (total_export$commodity == 30617)] / codes$total_netweight_kg[codes$country == 'Colombia'], digits = 3 )
codes$`030617`[codes$country == 'Ecuador'] <- round( total_export$netweight_kg[(total_export$country == 'Ecuador') & (total_export$commodity == 30617)] / codes$total_netweight_kg[codes$country == 'Ecuador'], digits = 3 )
codes$`030617`[codes$country == 'Peru'] <- round( total_export$netweight_kg[(total_export$country == 'Peru') & (total_export$commodity == 30617)] / codes$total_netweight_kg[codes$country == 'Peru'], digits = 3 )
codes$`030617`[codes$country == 'Indonesia'] <-round( total_export$netweight_kg[(total_export$country == 'Indonesia') & (total_export$commodity == 30617)] / codes$total_netweight_kg[codes$country == 'Indonesia'], digits = 3 )
codes$`030617`[codes$country == 'India'] <- round( total_export$netweight_kg[(total_export$country == 'India') & (total_export$commodity == 30617)] / codes$total_netweight_kg[codes$country == 'India'], digits = 3 )
codes$`030617`[codes$country == 'Viet Nam'] <- 0

```

```{r, echo = FALSE, results = 'asis'}

rownames(total_export) <- c()
kable(codes, caption = 'Percentage of 2016 export volume by HS code for requested countries')
```

